#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

exec 1>/tmp/metalware-default-output 2>&1

# Example of using rendered Metalware file; this file itself also uses other
# rendered files.
curl <%= node.files.main.first.url %> | /bin/bash

curl <%= node.build_complete_url %>
