networks:
  ext:
    defined: true
    domain: ext
    ip: 10.101.100.66
    network: 10.101.0.0
    netmask: 255.255.0.0
    gateway: 10.101.0.1
    short_hostname: <%= node.name %>.<%= config.networks.ext.domain %>
    interface: ext
    firewallpolicy: external
    bridge:
      interface: ext
      slave_interfaces: em4
