networks:
  pri:
    defined: true
    ip: 10.10.100.<%= node.index %>
    network: 10.10.0.0
    netmask: 255.255.0.0
    interface: em1
  ib:
    defined: true
    ip: 10.12.100.<%= node.index %>
    network: 10.12.0.0
    netmask: 255.255.0.0
    interface: em2
  bmc:
    defined: true
    ip: 10.11.100.<%= node.index %>
    network: 10.11.0.0
    netmask: 255.255.0.0
    interface: bmc
flightdirect: true
